rke_cloud_provider_config:
  name: openstack
  openstackCloudProvider:
    global:
      auth-url: http://172.16.10.2:5000/v3/
      username: "{{ lookup('env', 'os_username') }}"
      password: "{{ lookup('env', 'os_password') }}"
      region: RegionOne
      tenant-id: "{{ lookup('env', 'os_tenant_id') }}"
      domain-name: Default
    block_storage:
      bs-version: v2
      trust-device-path: true
    load_balancer:
      subnet-id: "{{ lookup('env', 'os_lb_subnet_id') }}"
      floating-network-id: "{{ lookup('env', 'os_floating_network_id') }}"

# Use the addons to install the default storage class
rke_cloud_provider_addons: |-
  ---
  apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
    name: standard
    annotations:
      "storageclass.kubernetes.io/is-default-class": "true"
  provisioner: kubernetes.io/cinder